[lab-2] Add slider and timer
UserNameMax/effective-web-course pull request #2
Opened 2022-11-03 06:54 UTC by UserNameMax

2022-11-03 07:06 UTC, konstantinzelinsky requested changes
В слайдере при ручном переключении слайда таймер для автоматического переключения должен сбрасываться, чтобы не получилось 2 переключения подряд.
В таймере при нажатии на `stop` должны быть доступны для нажатия только кнопки `start` и `reset`

2022-11-03 07:06 UTC, konstantinzelinsky commented on Lab2/slider/style.css
> +/*body{
От закомментированного кода нужно стараться избавляться

2022-11-03 07:06 UTC, konstantinzelinsky commented
Также советую использовать prettier для форматирования

2022-11-03 09:48 UTC, UserNameMax commented
Здравствуйте, всё поправил

2022-11-03 12:09 UTC, konstantinzelinsky commented
Подскажи, пожалуйста, имя, фамилию) И в будущем указывай в описании PR

2022-11-03 12:13 UTC, konstantinzelinsky commented
В таймере при нажатии на stop должны быть доступны для нажатия только кнопки start и reset
Таймер не полностью сохраняет свой стейт при перезагрузке страницы (не продолжает идти)

Не вижу фиксов для этого

2022-11-04 07:05 UTC, UserNameMax commented
Таймер исправил. Не сразу понял как стоп должен работать просто. 
Зовут меня Максим Мищенко.

2022-11-04 09:25 UTC, konstantinzelinsky approved these changes
Принял. 14 баллов.
На будущее 
- лучше использовать шаблонные строки вместо конкатенации
- для неизменяемых переменных использовать const вместо let

2022-11-04 09:25 UTC, merged